version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq-container"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "/path/to/local/folder:/var/lib/rabbitmq/mnesia"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
